language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r requirements/test.txt --use-mirrors
    - python setup.py develop
script: flake8 addonreg && nosetests -sv --with-coverage --cover-package=addonreg addonreg

notifications:
    email:
        - alexis@mozilla.com
    irc: "irc.mozilla.org#services-dev"
    on_success: change
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
